118 css for homepage mobile adaptation
Goteborgs-guiden/Gotehenburg-guide pull request #178
Opened 2023-10-27 13:59 UTC by xCandyFun

I hope that both the homepage and the mobile adaptation are looking good.

2023-10-29 15:20 UTC, BobHogvall requested changes
Good progress! Some things that might need looking over: 
The trams look very small on my computer and they should take up the entire page. 
The backgrounds on the trams shouldn't be as dark as they are now.
The middle trams isn't really centered in with the background. 
The right arrow overflows the screen on my computer when I look at the mobile version. 

But great work on the mobile adaption, I'm really not looking forward to doing that myself! Keep fighting!

2023-10-29 17:53 UTC, xCandyFun commented
I have now update the CSS for homepage and I don't see any overflow for the right arrow on my computer. Maybe send a picture of the problem.

2023-10-30 10:50 UTC, BobHogvall requested changes
Very good! The arrows seem fine now so it might have been an issue with my computer (it really is struggling). 
The trams are still quite small on the mobile version for me. Is it possible to change this? 
I'd like for the button to be more adapted to the screen as well, perhaps look at the figma.

2023-10-30 14:27 UTC, BobHogvall approved these changes

2023-10-30 14:27 UTC, merged